server:
  port: 8081
spring:
  application:
    name: item-servie
  datasource:
    url: jdbc:mysql://localhost:3306/yun6
    username: root
    password: root112233
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1